# Generated by Django 5.2 on 2025-04-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file_name',
            new_name='file',
        ),
    ]
