# Generated by Django 5.2.1 on 2025-06-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_rename_file_name_filemodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='title',
            new_name='researcher',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='topic',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
