# Generated by Django 5.2.1 on 2025-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_filemodel_researcher_alter_filemodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='field',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Languages', 'Languages'), ('Social Sciences', 'Social Sciences')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='researcher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
