# Generated by Django 5.2.1 on 2025-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_filemodel_field_alter_filemodel_researcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='field',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Languages', 'Languages'), ('Social', 'Social Studies')], default='General', max_length=100),
        ),
    ]
