# Generated by Django 5.2.1 on 2025-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_filemodel_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='converted_pdfs/'),
        ),
    ]
