# Generated by Django 5.2.1 on 2025-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_alter_filemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='chapter',
            field=models.CharField(default='Loading...', max_length=200),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
