# Generated by Django 5.2.1 on 2025-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_filemodel_chapter_alter_filemodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='chapter',
            field=models.CharField(blank=True, default='Loading...', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='field',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Languages', 'Languages'), ('Social', 'Social Studies')], default='General', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='researcher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
