# Generated by Django 5.2.1 on 2025-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_filemodel_chapter_alter_filemodel_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='field',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Technical', 'Technical'), ('Social', 'Social Studies')], default='Science', max_length=100),
        ),
    ]
