# Generated by Django 5.2.1 on 2025-10-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_alter_filemodel_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
